version: 0.2

phases:
  install:
    commands:
      # Si tu proyecto tiene dependencias o necesita alguna herramienta, puedes instalarla aquí.
      # Por ejemplo, si usas Node.js para algún preprocesamiento:
      # - npm install
    
  pre_build:
    commands:
      # Aquí puedes ejecutar comandos antes de construir, como linting o pruebas unitarias.
      # Por ejemplo:
      # - npm test
      - echo "Iniciando la fase pre_build..."
      - echo "Modificando el contenido de index.html"
      # Esta sentencia 'sed' busca la cadena "fácil y rápido" y la reemplaza.
      # La opción '-i' edita el archivo in-place.
      # - sed -i 's/fácil y rápido/(desde build) fácil y rápido/g' index.html
      - echo "Contenido de index.html modificado."

  build:
    commands:
      # En este ejemplo simple, no hay una "construcción" real para un sitio estático.
      # Simplemente copiamos los archivos que queremos desplegar.
      # Si tuvieras un proceso de compilación (ej. Webpack, Gulp), lo ejecutarías aquí.
      - echo "Iniciando la fase de construcción..."
      - echo "Copiando archivos HTML, CSS, JS e imágenes a la carpeta de artefactos."

  post_build:
    commands:
      # Aquí puedes realizar cualquier limpieza o pasos finales.
      - echo "La fase de construcción ha terminado."

artifacts:
  files:
    # Especifica los archivos y directorios que deseas incluir en los artefactos de salida.
    # Estos serán los archivos que CodePipeline desplegará a S3.
    - 'index.html'
    - 'css/**/*'  # Incluye todos los archivos en el directorio 'css' y sus subdirectorios
    - 'js/**/*'   # Incluye todos los archivos en el directorio 'js' y sus subdirectorios
    - 'images/**/*' # Incluye todos los archivos en el directorio 'images' y sus subdirectorios
    # Agrega cualquier otro archivo o directorio estático que necesites desplegar
    # - 'otro_archivo.txt'
    # - 'otra_carpeta/**/*'
  
  # Si tus artefactos deben ir a un directorio específico dentro del bucket S3, puedes especificarlo aquí.
  # discard-paths: yes # Si estableces esto en 'yes', los archivos se colocarán en la raíz del bucket S3.
  # base-directory: 'dist' # Si tu proceso de construcción genera archivos en una carpeta 'dist', por ejemplo.
